Update run

diff --git a/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run b/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
--- a/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
+++ b/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/init-wireguard-confs/run
@@ -1,282 +1,84 @@
 #!/usr/bin/with-contenv bashio
 # shellcheck shell=bash
-# shellcheck disable=SC2016,SC1091,SC2183
+set -e
 
-bashio::log.info "**** Init wireguard confs ****"
+WIREGUARD_STATE_DIR="/var/run/wireguard"
+QBT_CONFIG_FILE="/config/qBittorrent/qBittorrent.conf"
+declare wireguard_config=""
+declare wireguard_runtime_config=""
+declare configured_name
 
-mkdir -p /config/wireguard
+mkdir -p "${WIREGUARD_STATE_DIR}"
 
-# migration to subfolder for wg confs
-if [[ -z "$(ls -A /config/wireguard)" ]] && [[ -f /config/wg0.conf ]]; then
-    echo "**** Performing migration to new folder structure for confs. Please see the image changelog 2023-10-03 entry for more details. ****"
-    cp /config/wg0.conf /config/wireguard/wg0.conf
-    rm -rf /config/wg0.conf || :
+if ! bashio::config.true 'wireguard_enabled'; then
+    rm -f "${WIREGUARD_STATE_DIR}/config" "${WIREGUARD_STATE_DIR}/interface"
+    exit 0
 fi
 
-# prepare templates
-if [[ ! -f /config/templates/server.conf ]]; then
-    cp /defaults/server.conf /config/templates/server.conf
-fi
-if [[ ! -f /config/templates/peer.conf ]]; then
-    cp /defaults/peer.conf /config/templates/peer.conf
-fi
-# add preshared key to user templates (backwards compatibility)
-if ! grep -q 'PresharedKey' /config/templates/peer.conf; then
-    sed -i 's|^Endpoint|PresharedKey = \$\(cat /config/\${PEER_ID}/presharedkey-\${PEER_ID}\)\nEndpoint|' /config/templates/peer.conf
+if bashio::config.true 'openvpn_enabled'; then
+    bashio::exit.nok 'OpenVPN and WireGuard cannot be enabled simultaneously. Disable one of them.'
 fi
 
-generate_confs () {
-    mkdir -p /config/server
-    if [[ ! -f /config/server/privatekey-server ]]; then
-        umask 077
-        wg genkey | tee /config/server/privatekey-server | wg pubkey > /config/server/publickey-server
-    fi
-    eval "$(printf %s)
-    cat <<DUDE > /config/wireguard/wg0.conf
-$(cat /config/templates/server.conf)
+if bashio::config.true 'openvpn_alt_mode'; then
+    bashio::log.warning 'The openvpn_alt_mode option is ignored when WireGuard is enabled.'
+fi
 
-DUDE"
-    for i in "${PEERS_ARRAY[@]}"; do
-        if [[ ! "${i}" =~ ^[[:alnum:]]+$ ]]; then
-            echo "**** Peer ${i} contains non-alphanumeric characters and thus will be skipped. No config for peer ${i} will be generated. ****"
-        else
-            if [[ "${i}" =~ ^[0-9]+$ ]]; then
-                PEER_ID="peer${i}"
-            else
-                PEER_ID="peer_${i}"
-            fi
-            mkdir -p "/config/${PEER_ID}"
-            if [[ ! -f "/config/${PEER_ID}/privatekey-${PEER_ID}" ]]; then
-                umask 077
-                wg genkey | tee "/config/${PEER_ID}/privatekey-${PEER_ID}" | wg pubkey > "/config/${PEER_ID}/publickey-${PEER_ID}"
-                wg genpsk > "/config/${PEER_ID}/presharedkey-${PEER_ID}"
-            fi
-            if [[ -f "/config/${PEER_ID}/${PEER_ID}.conf" ]]; then
-                CLIENT_IP=$(grep "Address" "/config/${PEER_ID}/${PEER_ID}.conf" | awk '{print $NF}')
-                if [[ -n "${ORIG_INTERFACE}" ]] && [[ "${INTERFACE}" != "${ORIG_INTERFACE}" ]]; then
-                    CLIENT_IP="${CLIENT_IP//${ORIG_INTERFACE}/${INTERFACE}}"
-                fi
-            else
-                for idx in {2..254}; do
-                PROPOSED_IP="${INTERFACE}.${idx}"
-                if ! grep -q -R "${PROPOSED_IP}" /config/peer*/*.conf 2>/dev/null && ([[ -z "${ORIG_INTERFACE}" ]] || ! grep -q -R "${ORIG_INTERFACE}.${idx}" /config/peer*/*.conf 2>/dev/null); then
-                    CLIENT_IP="${PROPOSED_IP}"
-                    break
-                fi
-                done
-            fi
-            if [[ -f "/config/${PEER_ID}/presharedkey-${PEER_ID}" ]]; then
-                # create peer conf with presharedkey
-                eval "$(printf %s)
-                cat <<DUDE > /config/${PEER_ID}/${PEER_ID}.conf
-$(cat /config/templates/peer.conf)
-DUDE"
-                # add peer info to server conf with presharedkey
-                cat <<DUDE >> /config/wireguard/wg0.conf
-[Peer]
-# ${PEER_ID}
-PublicKey = $(cat "/config/${PEER_ID}/publickey-${PEER_ID}")
-PresharedKey = $(cat "/config/${PEER_ID}/presharedkey-${PEER_ID}")
-DUDE
-            else
-                echo "**** Existing keys with no preshared key found for ${PEER_ID}, creating confs without preshared key for backwards compatibility ****"
-                # create peer conf without presharedkey
-                eval "$(printf %s)
-                cat <<DUDE > /config/${PEER_ID}/${PEER_ID}.conf
-$(sed '/PresharedKey/d' "/config/templates/peer.conf")
-DUDE"
-                # add peer info to server conf without presharedkey
-                cat <<DUDE >> /config/wireguard/wg0.conf
-[Peer]
-# ${PEER_ID}
-PublicKey = $(cat "/config/${PEER_ID}/publickey-${PEER_ID}")
-DUDE
-            fi
-            SERVER_ALLOWEDIPS=SERVER_ALLOWEDIPS_PEER_${i}
-            # add peer's allowedips to server conf
-            if [[ -n "${!SERVER_ALLOWEDIPS}" ]]; then
-                echo "Adding ${!SERVER_ALLOWEDIPS} to wg0.conf's AllowedIPs for peer ${i}"
-                cat <<DUDE >> /config/wireguard/wg0.conf
-AllowedIPs = ${CLIENT_IP}/32,${!SERVER_ALLOWEDIPS}
-DUDE
-            else
-                cat <<DUDE >> /config/wireguard/wg0.conf
-AllowedIPs = ${CLIENT_IP}/32
-DUDE
-            fi
-            # add PersistentKeepalive if the peer is specified
-            if [[ -n "${PERSISTENTKEEPALIVE_PEERS_ARRAY}" ]] && ([[ "${PERSISTENTKEEPALIVE_PEERS_ARRAY[0]}" = "all" ]] || printf '%s\0' "${PERSISTENTKEEPALIVE_PEERS_ARRAY[@]}" | grep -Fxqz -- "${i}"); then
-                cat <<DUDE >> /config/wireguard/wg0.conf
-PersistentKeepalive = 25
-
-DUDE
-            else
-                cat <<DUDE >> /config/wireguard/wg0.conf
-
-DUDE
-            fi
-            if [[ -z "${LOG_CONFS}" ]] || [[ "${LOG_CONFS}" = "true" ]]; then
-                echo "PEER ${i} QR code (conf file is saved under /config/${PEER_ID}):"
-                qrencode -t ansiutf8 < "/config/${PEER_ID}/${PEER_ID}.conf"
-            else
-                echo "PEER ${i} conf and QR code png saved in /config/${PEER_ID}"
-            fi
-            qrencode -o "/config/${PEER_ID}/${PEER_ID}.png" < "/config/${PEER_ID}/${PEER_ID}.conf"
-        fi
-    done
-}
-
-save_vars () {
-    cat <<DUDE > /config/.donoteditthisfile
-ORIG_SERVERURL="$SERVERURL"
-ORIG_SERVERPORT="$SERVERPORT"
-ORIG_PEERDNS="$PEERDNS"
-ORIG_PEERS="$PEERS"
-ORIG_INTERFACE="$INTERFACE"
-ORIG_ALLOWEDIPS="$ALLOWEDIPS"
-ORIG_PERSISTENTKEEPALIVE_PEERS="$PERSISTENTKEEPALIVE_PEERS"
-DUDE
-}
-
-if [[ -n "$PEERS" ]]; then
-    echo "**** Server mode is selected ****"
-    if [[ "$PEERS" =~ ^[0-9]+$ ]] && ! [[ "$PEERS" = *,* ]]; then
-        mapfile -t PEERS_ARRAY < <(seq 1 "${PEERS}")
+if bashio::config.has_value 'wireguard_config'; then
+    configured_name="$(bashio::config 'wireguard_config')"
+    configured_name="${configured_name##*/}"
+    if [[ -z "${configured_name}" ]]; then
+        bashio::log.info 'wireguard_config option left empty. Attempting automatic selection.'
+    elif bashio::fs.file_exists "/config/wireguard/${configured_name}"; then
+        wireguard_config="/config/wireguard/${configured_name}"
     else
-        mapfile -t PEERS_ARRAY < <(echo "${PEERS}" | tr ',' '\n')
+        bashio::exit.nok "WireGuard configuration '/config/wireguard/${configured_name}' not found."
     fi
-    if [[ -n "${PERSISTENTKEEPALIVE_PEERS}" ]]; then
-        echo "**** PersistentKeepalive will be set for: ${PERSISTENTKEEPALIVE_PEERS/,/ } ****"
-        mapfile -t PERSISTENTKEEPALIVE_PEERS_ARRAY < <(echo "${PERSISTENTKEEPALIVE_PEERS}" | tr ',' '\n')
-    fi
-    if [[ -z "$SERVERURL" ]] || [[ "$SERVERURL" = "auto" ]]; then
-        SERVERURL=$(curl -s icanhazip.com)
-        echo "**** SERVERURL var is either not set or is set to \"auto\", setting external IP to auto detected value of $SERVERURL ****"
+fi
+
+if [ -z "${wireguard_config:-}" ]; then
+    mapfile -t configs < <(find /config/wireguard -maxdepth 1 -type f -name '*.conf' -print)
+    if [ "${#configs[@]}" -eq 0 ]; then
+        bashio::exit.nok 'WireGuard is enabled but no .conf file was found in /config/wireguard.'
+    elif [ "${#configs[@]}" -eq 1 ]; then
+        wireguard_config="${configs[0]}"
+        bashio::log.info "WireGuard configuration not specified. Using ${wireguard_config##*/}."
+    elif bashio::fs.file_exists '/config/wireguard/config.conf'; then
+        wireguard_config='/config/wireguard/config.conf'
+        bashio::log.info 'Using default WireGuard configuration config.conf.'
     else
-        echo "**** External server address is set to $SERVERURL ****"
+        bashio::exit.nok "Multiple WireGuard configuration files detected. Please set the 'wireguard_config' option."
     fi
-    SERVERPORT=${SERVERPORT:-51820}
-    echo "**** External server port is set to ${SERVERPORT}. Make sure that port is properly forwarded to port 51820 inside this container ****"
-    INTERNAL_SUBNET=${INTERNAL_SUBNET:-10.13.13.0}
-    echo "**** Internal subnet is set to $INTERNAL_SUBNET ****"
-    INTERFACE=$(echo "$INTERNAL_SUBNET" | awk 'BEGIN{FS=OFS="."} NF--')
-    ALLOWEDIPS=${ALLOWEDIPS:-0.0.0.0/0, ::/0}
-    echo "**** AllowedIPs for peers $ALLOWEDIPS ****"
-    if [[ -z "$PEERDNS" ]] || [[ "$PEERDNS" = "auto" ]]; then
-        PEERDNS="${INTERFACE}.1"
-        echo "**** PEERDNS var is either not set or is set to \"auto\", setting peer DNS to ${INTERFACE}.1 to use wireguard docker host's DNS. ****"
-    else
-        echo "**** Peer DNS servers will be set to $PEERDNS ****"
-    fi
-    if [[ ! -f /config/wireguard/wg0.conf ]]; then
-        echo "**** No wg0.conf found (maybe an initial install), generating 1 server and ${PEERS} peer/client confs ****"
-        generate_confs
-        save_vars
-    else
-        echo "**** Server mode is selected ****"
-        if [[ -f /config/.donoteditthisfile ]]; then
-            . /config/.donoteditthisfile
-        fi
-        if [[ "$SERVERURL" != "$ORIG_SERVERURL" ]] || [[ "$SERVERPORT" != "$ORIG_SERVERPORT" ]] || [[ "$PEERDNS" != "$ORIG_PEERDNS" ]] || [[ "$PEERS" != "$ORIG_PEERS" ]] || [[ "$INTERFACE" != "$ORIG_INTERFACE" ]] || [[ "$ALLOWEDIPS" != "$ORIG_ALLOWEDIPS" ]] || [[ "$PERSISTENTKEEPALIVE_PEERS" != "$ORIG_PERSISTENTKEEPALIVE_PEERS" ]]; then
-            echo "**** Server related environment variables changed, regenerating 1 server and ${PEERS} peer/client confs ****"
-            generate_confs
-            save_vars
-        else
-            echo "**** No changes to parameters. Existing configs are used. ****"
-        fi
-    fi
+fi
+
+dos2unix "${wireguard_config}" >/dev/null 2>&1 || true
+
+interface_name="$(basename "${wireguard_config}" .conf)"
+if [[ -z "${interface_name}" ]]; then
+    interface_name='wg0'
+fi
+
+wireguard_runtime_config="${WIREGUARD_STATE_DIR}/${interface_name}.conf"
+
+cp "${wireguard_config}" "${wireguard_runtime_config}"
+chmod 600 "${wireguard_runtime_config}" 2>/dev/null || true
+bashio::log.info 'Prepared WireGuard runtime configuration for initial connection attempt.'
+
+echo "${wireguard_runtime_config}" > "${WIREGUARD_STATE_DIR}/config"
+echo "${interface_name}" > "${WIREGUARD_STATE_DIR}/interface"
+
+if bashio::fs.file_exists "${QBT_CONFIG_FILE}"; then
+    sed -i '/Interface/d' "${QBT_CONFIG_FILE}"
+    sed -i "/\\[Preferences\\]/ i\\Connection\\\\Interface=${interface_name}" "${QBT_CONFIG_FILE}"
+    sed -i "/\\[Preferences\\]/ i\\Connection\\\\InterfaceName=${interface_name}" "${QBT_CONFIG_FILE}"
+    sed -i "/\\[BitTorrent\\]/a \\Session\\\\Interface=${interface_name}" "${QBT_CONFIG_FILE}"
+    sed -i "/\\[BitTorrent\\]/a \\Session\\\\InterfaceName=${interface_name}" "${QBT_CONFIG_FILE}"
 else
-    echo "**** Client mode selected. ****"
-    USE_COREDNS="${USE_COREDNS,,}"
-    printf %s "${USE_COREDNS:-false}" > /run/s6/container_environment/USE_COREDNS
-
-    ####### alexbelgium scrips#######
-    WIREGUARD_STATE_DIR="/var/run/wireguard"
-    QBT_CONFIG_FILE="/config/qBittorrent/qBittorrent.conf"
-    declare wireguard_config=""
-    declare wireguard_runtime_config=""
-    declare configured_name
-
-    mkdir -p "${WIREGUARD_STATE_DIR}"
-
-    if ! bashio::config.true 'wireguard_enabled'; then
-        rm -f "${WIREGUARD_STATE_DIR}/config" "${WIREGUARD_STATE_DIR}/interface" "${WIREGUARD_IPV6_STATE_FILE}"
-        exit 0
-    fi
-
-    if bashio::config.true 'openvpn_enabled'; then
-        bashio::exit.nok 'OpenVPN and WireGuard cannot be enabled simultaneously. Disable one of them.'
-    fi
-
-    if bashio::config.true 'openvpn_alt_mode'; then
-        bashio::log.warning 'The openvpn_alt_mode option is ignored when WireGuard is enabled.'
-    fi
-
-    if bashio::config.has_value 'wireguard_config'; then
-        configured_name="$(bashio::config 'wireguard_config')"
-        configured_name="${configured_name##*/}"
-        if [[ -z "${configured_name}" ]]; then
-            bashio::log.info 'wireguard_config option left empty. Attempting automatic selection.'
-        elif bashio::fs.file_exists "/config/wireguard/${configured_name}"; then
-            wireguard_config="/config/wireguard/${configured_name}"
-        else
-            bashio::exit.nok "WireGuard configuration '/config/wireguard/${configured_name}' not found."
-        fi
-    fi
-
-    if [ -z "${wireguard_config:-}" ]; then
-        mapfile -t configs < <(find /config/wireguard -maxdepth 1 -type f -name '*.conf' -print)
-        if [ "${#configs[@]}" -eq 0 ]; then
-            bashio::exit.nok 'WireGuard is enabled but no .conf file was found in /config/wireguard.'
-        elif [ "${#configs[@]}" -eq 1 ]; then
-            wireguard_config="${configs[0]}"
-            bashio::log.info "WireGuard configuration not specified. Using ${wireguard_config##*/}."
-        elif bashio::fs.file_exists '/config/wireguard/config.conf'; then
-            wireguard_config='/config/wireguard/config.conf'
-            bashio::log.info 'Using default WireGuard configuration config.conf.'
-        else
-            bashio::exit.nok "Multiple WireGuard configuration files detected. Please set the 'wireguard_config' option."
-        fi
-    fi
-
-    dos2unix "${wireguard_config}" >/dev/null 2>&1 || true
-
-    interface_name="$(basename "${wireguard_config}" .conf)"
-    if [[ -z "${interface_name}" ]]; then
-        interface_name='wg0'
-    fi
-
-    wireguard_runtime_config="${WIREGUARD_STATE_DIR}/${interface_name}.conf"
-
-    cp "${wireguard_config}" "${wireguard_runtime_config}"
-    chmod 600 "${wireguard_runtime_config}" 2>/dev/null || true
-    bashio::log.info 'Prepared WireGuard runtime configuration copy. Performing compatibility checks next.'
-
-    echo "${wireguard_runtime_config}" > "${WIREGUARD_STATE_DIR}/config"
-    echo "${interface_name}" > "${WIREGUARD_STATE_DIR}/interface"
-
-    if bashio::fs.file_exists "${QBT_CONFIG_FILE}"; then
-        sed -i '/Interface/d' "${QBT_CONFIG_FILE}"
-        sed -i "/\\[Preferences\\]/ i\\Connection\\\\Interface=${interface_name}" "${QBT_CONFIG_FILE}"
-        sed -i "/\\[Preferences\\]/ i\\Connection\\\\InterfaceName=${interface_name}" "${QBT_CONFIG_FILE}"
-        sed -i "/\\[BitTorrent\\]/a \\Session\\\\Interface=${interface_name}" "${QBT_CONFIG_FILE}"
-        sed -i "/\\[BitTorrent\\]/a \\Session\\\\InterfaceName=${interface_name}" "${QBT_CONFIG_FILE}"
-    else
-        bashio::log.warning "qBittorrent config file not found. Bind the client manually to interface ${interface_name}."
-    fi
-
-    # Get current ip
-    curl -4 -s ipecho.net/plain > /currentipv4
-    curl -6 -s ipecho.net/plain > /currentipv6
-
-    bashio::log.info "WireGuard prepared with interface ${interface_name} using configuration ${wireguard_config##*/}."
+    bashio::log.warning "qBittorrent config file not found. Bind the client manually to interface ${interface_name}."
 fi
 
-# set up CoreDNS
-if [[ ! -f /config/coredns/Corefile ]]; then
-    cp /defaults/Corefile /config/coredns/Corefile
-fi
+# Get current ip
+( curl -fsS --max-time 10 https://ifconfig.co/ip \
+|| curl -fsS --max-time 10 https://api64.ipify.org \
+|| curl -fsS --max-time 10 https://ipecho.net/plain ) > /currentip
 
-# permissions
-lsiown -R abc:abc \
-    /config
+bashio::log.info "WireGuard prepared with interface ${interface_name} using configuration ${wireguard_config##*/}."
