Update run

diff --git a/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/svc-wireguard/run b/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/svc-wireguard/run
--- a/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/svc-wireguard/run
+++ b/qbittorrent-wireguard/root/etc/s6-overlay/s6-rc.d/svc-wireguard/run
@@ -1,46 +1,48 @@
 #!/usr/bin/with-contenv bashio
 # shellcheck shell=bash
 
-unset WG_CONFS
-rm -rf /run/activeconfs
-# Enumerate interfaces
-for wgconf in /config/wg_confs/*.conf; do
-    if grep -q "\[Interface\]" "${wgconf}"; then
-        bashio::log.info "**** Found WG conf ${wgconf}, adding to list ****"
-        WG_CONFS+=("${wgconf}")
-    else
-        bashio::log.warning "**** Found WG conf ${wgconf}, but it doesn't seem to be valid, skipping. ****"
-    fi
-done
+if bashio::config.true 'wireguard_enabled'; then
+  unset WG_CONFS
+  rm -rf /run/activeconfs
+  # Enumerate interfaces
+  for wgconf in /config/wg_confs/*.conf; do
+      if grep -q "\[Interface\]" "${wgconf}"; then
+          bashio::log.info "**** Found WG conf ${wgconf}, adding to list ****"
+          WG_CONFS+=("${wgconf}")
+      else
+          bashio::log.warning "**** Found WG conf ${wgconf}, but it doesn't seem to be valid, skipping. ****"
+      fi
+  done
 
-if [[ -z "${WG_CONFS[*]}" ]]; then
-    bashio::log.warning "**** No valid tunnel config found. Please create a valid config and restart the container ****"
-    ip route del default
-    exit 0
-fi
+  if [[ -z "${WG_CONFS[*]}" ]]; then
+      bashio::log.warning "**** No valid tunnel config found. Please create a valid config and restart the container ****"
+      ip route del default
+      exit 0
+  fi
 
-unset FAILED
-for tunnel in "${WG_CONFS[@]}"; do
-    bashio::log.info "**** Activating tunnel ${tunnel} ****"
-    if ! wg-quick up "${tunnel}"; then
-        FAILED="${tunnel}"
-        break
-    fi
-done
+  unset FAILED
+  for tunnel in "${WG_CONFS[@]}"; do
+      bashio::log.info "**** Activating tunnel ${tunnel} ****"
+      if ! wg-quick up "${tunnel}"; then
+          FAILED="${tunnel}"
+          break
+      fi
+  done
 
-if [[ -z "${FAILED}" ]]; then
-    declare -p WG_CONFS > /run/activeconfs
-    bashio::log.info "**** All tunnels are now active ****"
-else
-    bashio::log.warning "**** Tunnel ${FAILED} failed, will stop all others! ****"
-    for tunnel in "${WG_CONFS[@]}"; do
-        if [[ "${tunnel}" = "${FAILED}" ]]; then
-            break
-        else
-            bashio::log.warning "**** Disabling tunnel ${tunnel} ****"
-            wg-quick down "${tunnel}" || :
-        fi
-    done
-    ip route del default
-    bashio::log.warning "**** All tunnels are now down. Please fix the tunnel config ${FAILED} and restart the container ****"
+  if [[ -z "${FAILED}" ]]; then
+      declare -p WG_CONFS > /run/activeconfs
+      bashio::log.info "**** All tunnels are now active ****"
+  else
+      bashio::log.warning "**** Tunnel ${FAILED} failed, will stop all others! ****"
+      for tunnel in "${WG_CONFS[@]}"; do
+          if [[ "${tunnel}" = "${FAILED}" ]]; then
+              break
+          else
+              bashio::log.warning "**** Disabling tunnel ${tunnel} ****"
+              wg-quick down "${tunnel}" || :
+          fi
+      done
+      ip route del default
+      bashio::log.warning "**** All tunnels are now down. Please fix the tunnel config ${FAILED} and restart the container ****"
+  fi
 fi
